# ansible/inventories/prod/hosts.yml
# Production environment inventory
# IP will be populated by Jenkins from Terraform output

all:
  hosts:
    app_server:
      ansible_host: "{{ server_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ ssh_key_path | default('~/.ssh/freights-prod-key.pem') }}"
  vars:
    env: prod
    docker_registry: docker.io
    dockerhub_username: theenukabandara
