# ansible/inventories/dev/hosts.yml
# Development environment inventory
# IP will be populated by Jenkins from Terraform output

all:
  hosts:
    app_server:
      ansible_host: "{{ server_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ ssh_key_path | default('~/.ssh/freights-dev-key.pem') }}"
  vars:
    env: dev
    docker_registry: docker.io
    dockerhub_username: theenukabandara
